# Day 2

#### List Comprehesion

In [1]:
squares = [x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


#### Nested List

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9,]]
flat_list = [num for row in matrix for num in row]
print(flat_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
evn_squares = [x**2 for x in range(10) if x%2 == 0]
print(evn_squares)

[0, 4, 16, 36, 64]


#### Lambda Function

In [5]:
add = lambda x,y : x + y
print(add(5,3))

8


#### Map Function

In [8]:
numbers = [1,2,3,4,5]
squared = list(map(lambda x :  x**2, numbers))
print(squared)

[1, 4, 9, 16, 25]


#### Filter Function

In [11]:
numbers = [1,2,3,4,5]
evn_numbers = list(filter(lambda x : x%2 == 0, numbers))
print(evn_numbers)

[2, 4]


#### Decorators

In [19]:
def my_decorators(func):
    def wrapper ():
        print("Something is happening before the function is called")
        func()
        print("Something is happening after the function is called")
    return wrapper
@my_decorators
def say_hello():
    print("Hello!")
say_hello()

Something is happening before the function is called
Hello!
Something is happening after the function is called


In [ ]:
def repeat(num_times):
    def decorators_repeat(func):
        def wrapper(*args, **kwargs):
            for _ in range(num_times):
                func(*args, **kwargs)
            return wrapper
        return decorator_repeat
@ repeat(num_times=3)
def greet(name):
    print(f"Hello {name}"):
greet('Alice')

In [23]:
def count_up_to(max):
    count = 1
    while count <= max:
         count
        count += 1
counter= count_up_to(5)
for number in counter:
    print(number,end=' ')

1 2 3 4 5 

## Numpy

In [1]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

# Creating a 2D array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

# Creating zero array
zeros_aray = np.zeros((3, 3))
print(zeros_aray)

# Arange function
range_array = np.arange(0,10,2)
print(range_array)

# Linspace
linspace_array = np.linspace(0,1,5)
print(linspace_array)

# Identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

# Random.Rand and Random.RandInt
random_array = np.random.rand(3)
print(random_array)
random_array1 = np.random.randint(3)
print(random_array1)

# Basic Operation
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# ADDITION
result_add = arr1 + arr2
print(result_add)

# SUBTRACTION
result_subtract = arr1 - arr2
print(result_subtract)

# MULTIPLICATION
result_multiply = arr1 * arr2
print(result_multiply)

# DIVISION
result_division = arr1 / arr2
print(result_division)

# Basic Functions
import numpy as np
arr = np.array([1,2,3,4,5])
sqrt = np.sqrt(arr)
exp = np.exp(arr)
mean = np.mean(arr)
add = np.sum(arr)
sin = np.sin(arr)
print(sqrt)
print(exp)
print(mean)
print(add)
print(sin)

# Dot and Element Multiplication
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
dot = np.dot(arr1,arr2)
ele_mult = arr1 * arr2
print(dot)
print(ele_mult)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Pandas 

In [4]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

data = [1,2,3,4,5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
print(series)

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Dave'],
    'Age': [21, 22, 23, 24],
    'City': ['London', 'Paris', 'Berlin', 'Bern']
}
df = pd.DataFrame(data)
print(df)

# Importing data from a CSV file
df = pd.read_csv('/home/developer/Desktop/test.csv')
print(df)

# Importing data from an Excel file
df1 = pd.read_excel('/home/developer/Desktop/test.xlsx')
print(df1)

# # Importing data from JSON file
# df2 = pd.read_json('/home/developer/Desktop/test.json')
# print(df2)

# # Importing data from SQL file
# import sqlite3
# conn = sqlite3.connect('test.db')
# df3 = pd.read_sql_query('SELECT a FROM table_name',conn)
# print(df3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
      Name  Age    City
0    Alice   21  London
1      Bob   22   Paris
2  Charlie   23  Berlin
3     Dave   24    Bern
   Roll No Name
0        1   AA
1        2   BB
2        3   CC
3        4   DD
4        5   EE
5        6   FF
6        7   GG
7        8   HH
   Roll No  Name
0         1   AA
1         2   BB
2         3   CC
3         4   DD
4         5   EE
